### ISSUE TITLE
是否可以增加  去广告和阿里云插件

### ISSUE THREAD

**Issue by rogeryingjunwei** [sbwml/nanopi-r5s-openwrt#1]
是否可以增加  去广告和阿里云插件，非常感谢！相信R5S会越来越好！

**Comment by sbwml** [comment]
其实如果你认真细看，他都有了。
去广告：开启mosdns，勾选最后面的去广告
阿里云：网络存储-Alist ，挂阿里云盘（这玩意支持web 和 webdav）

**Comment by sbwml** [comment]
如果你说的阿里云插件是ddns，那对应的就是  “服务  -  动态dns  -   添加aliyun.com
